# theme = 'autumn_night'
# theme = 'catppuccin_mocha'
theme = 'my_theme'

[editor]
# FIXME: enable on next release after v23.05
# line-ending = 'lf'
idle-timeout = 50
line-number = 'relative'
scrolloff = 20
shell = ['pwsh', '-NoLogo', '-NonInteractive', '-Command'] #-NoProfile
true-color = true

[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.auto-pairs]
"'" = "'"
# '<' = '>'
# '`' = '`'
'"' = '"'
'(' = ')'
'[' = ']'
'{' = '}'

[editor.statusline]
separator = '|'
left = ['position', 'position-percentage', 'selections', 'diagnostics']
center = ['file-name', 'total-line-numbers']
right = ['spinner', 'workspace-diagnostics', 'version-control', 'file-line-ending']

[editor.lsp]
display-inlay-hints = true

[keys.normal]
# C-e = ['window_mode']
C-f = 'file_picker'
C-h = 'jump_view_left'
C-j = 'jump_view_up'
C-k = 'jump_view_down'
C-l = 'jump_view_right'
C-r = 'goto_last_accessed_file'
C-s = ':w'
C-tab = ':buffer-next'
C-w = ':buffer-close'
P = ':clipboard-paste-before'
R = ':clipboard-paste-replace'
d = [':clipboard-yank', 'delete_selection_noyank']
p = ':clipboard-paste-after'
y = ':clipboard-yank'

[keys.normal.'space']
o = 'file_picker_in_current_buffer_directory'

[keys.select]
C-s = ':w'
P = 'paste_after'
R = ':clipboard-paste-replace'
Y = 'yank'
d = [':clipboard-yank', 'delete_selection_noyank']
y = ':clipboard-yank'

[keys.insert]
C-h = 'jump_view_left'
C-j = 'jump_view_up'
C-k = 'jump_view_down'
C-l = 'jump_view_right'
C-r = 'goto_last_accessed_file'
C-s = [':w', 'normal_mode']
C-space = 'completion'
C-tab = ':buffer-next'
C-v = ['normal_mode', ':clipboard-paste-before', 'insert_mode']
